name: okk
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Find and Replace
        uses: jacobtomlinson/gha-find-replace@master
        with:
          find: "https://github.com/quiec/asenauserbot"
          replace: "https://www.github.com/THUGSOP/SPAM"
      - name: Pull All Updates
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'omk'
          commit_options: '--no-verify'
          repository: .
          commit_user_name: THUGSOP
          commit_user_email: opgangster232@gmail.com
          commit_author: THUGSOP <opgangster232@gmail.com>
